baseURL = "https://civic.vision/geospatial-data-visualization-with-d3/"
languageCode = "en-us"
title = "Geospatial Data Visualization with d3"
theme = "civic"

[params]
  rightmessage = "1998050406"
  description = "This online video course on creating maps with d3.js helps you learn the geospatial concepts of d3 and how to create geospatial data visualizations with javascript. The course is taught by Mila Frerichs who is a geospatial data visualization consultant. The course is modeled from successful hands-on workshops at geospatial conferences over the last 4 years. "
  images = ["https://res.cloudinary.com/civicvision/image/upload/v1552905044/Landingpages/Geospatial%20d3/hexmap.png"]
  title = "Geospatial Data Visualization with d3"
