---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/examples
  label: Examples
  create: all
  match: "**/*"
- type: heading
  label: Articles
- type: directory
  path: content/tutorials
  label: tutorials
  create: all
  match: "**/*"
- type: directory
  path: content/tips
  label: tips
  create: all
  match: "**/*"
- type: heading
  label: Global
- type: directory
  path: content/resources/d3
  label: d3
  create: all
  match: "**/*"
  templates:
  - single-page
- type: directory
  path: content/resources
  label: Resources
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content
  label: All Pages
  create: all
  match: "**/*"
- type: directory
  path: content/f4gsd
  label: San Diego Workshop
  create: all
  match: "**/*"
- type: document
  path: data/resources/features/list.yml
  label: Features
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.54.0
